const auth = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_ERROR: 'SIGNOUT_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  SET_USER_ADMIN_STATUS: 'SET_USER_ADMIN_STATUS',
};

const theme = {
  CHANGE_TO_DARK_THEME: 'CHANGE_TO_DARK_THEME',
  CHANGE_TO_LIGHT_THEME: 'CHANGE_TO_LIGHT_THEME',
};

const actionNames = {
  auth,
  theme,
};

export default actionNames;
