const auth = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  SET_USER_ADMIN_STATUS: 'SET_USER_ADMIN_STATUS',
};

const admin = {
  SEARCH_USER_BY_EMAIL_SUCCESS: 'SEARCH_USER_BY_EMAIL_SUCCESS',
  SEARCH_USER_BY_EMAIL_FAIL: 'SEARCH_USER_BY_EMAIL_FAIL',
};

const actionNames = {
  auth,
  admin,
};

export default actionNames;
