export default {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  SET_USER_ADMIN_STATUS: 'SET_USER_ADMIN_STATUS',
  AUTH_ERROR: 'AUTH_ERROR',
};
