export default {
  ADD_COLLECTION_SUCCESS: 'ADD_COLLECTION_SUCCESS',
  FETCH_ONE_COLLECTION_SUCCESS: 'FETCH_ONE_COLLECTION_SUCCESS',
  FETCH_ALL_COLLECTIONS_SUCCESS: 'FETCH_ALL_COLLECTIONS_SUCCESS',
  UPDATE_COLLECTION_SUCCESS: 'UPDATE_COLLECTION_SUCCESS',
  DELETE_COLLECTION_SUCCESS: 'DELETE_COLLECTION_SUCCESS',
  SET_COLLECTION_NOTIFICATION_MESSAGE: 'SET_COLLECTION_NOTIFICATION_MESSAGE',
  REMOVE_COLLECTION_NOTIFICATION_MESSAGE:
    'REMOVE_COLLECTION_NOTIFICATION_MESSAGE',
  SET_COLLECTION_ERROR_MESSAGE: 'SET_COLLECTION_ERROR_MESSAGE',
  REMOVE_COLLECTION_ERROR_MESSAGE: 'REMOVE_COLLECTION_ERROR_MESSAGE',
};
