export default {
  SEARCH_USER_BY_EMAIL_SUCCESS: 'SEARCH_USER_BY_EMAIL_SUCCESS',
  SEARCH_USER_BY_Id_SUCCESS: 'SEARCH_USER_BY_Id_SUCCESS',
  UPDATE_USER_ADMIN_ROLE_SUCCESS: 'UPDATE_USER_ADMIN_ROLE_SUCCESS',
  ENABLE_DISABLE_USER_SUCCESS: 'ENABLE_DISABLE_USER_SUCCESS',
  FETCH_ALL_ADMINS_SUCCESS: 'FETCH_ALL_ADMINS_SUCCESS',
  FETCH_USERS_COUNT_SUCCESS: 'FETCH_USERS_COUNT_SUCCESS',
  FETCH_ADMINS_COUNT_SUCCESS: 'FETCH_ADMINS_COUNT_SUCCESS',
  ADMIN_DELETES_USER_SUCCESS: 'ADMIN_DELETES_USER_SUCCESS',
  REMOVE_NOTIFICATION_MESSAGE: 'REMOVE_NOTIFICATION_MESSAGE',
  HTTP_ERROR: 'HTTP_ERROR',
};
