export default {
  SEARCH_USER_BY_EMAIL_SUCCESS: 'SEARCH_USER_BY_EMAIL_SUCCESS',
  SEARCH_USER_BY_ID_SUCCESS: 'SEARCH_USER_BY_ID_SUCCESS',
  UPDATE_USER_ADMIN_ROLE_SUCCESS: 'UPDATE_USER_ADMIN_ROLE_SUCCESS',
  ENABLE_DISABLE_USER_SUCCESS: 'ENABLE_DISABLE_USER_SUCCESS',
  FETCH_ALL_ADMINS_SUCCESS: 'FETCH_ALL_ADMINS_SUCCESS',
  FETCH_USERS_COUNT_SUCCESS: 'FETCH_USERS_COUNT_SUCCESS',
  FETCH_ADMINS_COUNT_SUCCESS: 'FETCH_ADMINS_COUNT_SUCCESS',
  ADMIN_DELETES_USER_SUCCESS: 'ADMIN_DELETES_USER_SUCCESS',
  SET_ADMIN_ERROR_MESSAGE: 'SET_ADMIN_ERROR_MESSAGE',
  REMOVE_ADMIN_ERROR_MESSAGE: 'REMOVE_ADMIN_ERROR_MESSAGE',
};
